# -*- coding: utf-8 -*-
"""Despliegue del modelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5318USSMhdBrN_Q-dJpYOXiX9kk1ZZL

# Despliegue para Clasificación

- Cargamos el modelo
- Cargamos los datos futuros
- Preparamos los datos futuros
- Aplicamos el modelo para la predicción
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

#Cargamos el modelo
import pickle
filename = 'modelo.pkl'

modelo,labelencoder,variables,min_max_scaler = pickle.load(open(filename, 'rb'))

#datos=[['22',2.20,'MT',7,5.0,1,0.00146,'I',-39.118229]]
#data=pd.DataFrame(datos, columns=['Empresa ID',	'Horas',	'MT/BT',	'Clientes Afectados',	'kVA Afectados','Trans. Afectados','SAIFI',	'Tipif. interrupción'	,'latitud_punto_falla'])

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de tipo de fallas en equipos de distribución')

Horas = st.slider('Tiempo de la falla', min_value=0, max_value=450, value=20, step=1)
Clientes_Afectados = st.number_input('Clientes afectados')
kVA_afectados = st.number_input('kVA Afectados')
Trans_Afectados = st.number_input('Transformadores afectados')
SAIFI = st.number_input('SAIFI')
latitud = st.number_input('Latitud')
Empresa = st.selectbox('Empresa',['0','22','23','24','39'])
Tipif_interrupción = st.selectbox('Tipo interrupción',['-','E','I'])
MT_BT = st.selectbox('MT BT',['-','MT','BT'])


#Dataframe
datos = [[Horas,Clientes_Afectados,kVA_afectados,Trans_Afectados,SAIFI,latitud,Empresa,Tipif_interrupción,MT_BT]]
data = pd.DataFrame(datos, columns=['Horas', 'Clientes Afectados','kVA Afectados','Trans. Afectados','SAIFI','latitud_punto_falla','Empresa ID','Tipif. interrupción','MT/BT']) #Dataframe con los mismos nombres de variables

data_preparada=data.copy()
#En despliegue drop_first= False
# crear dummies para variables categoricas
columnas_categoricas = [
    "Empresa ID",
    #"Causa ID",
    "Tipif. interrupción",
    "MT/BT"
]
data_preparada = pd.get_dummies(data_preparada, columns=columnas_categoricas, drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

"""#**Predicciones**

El modelo presenta un error el 10%
"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Predicción']=labelencoder.inverse_transform(Y_pred)
data.head()